### ISSUE TITLE
Configure buttons

### ISSUE THREAD

**Issue by joaonc** [joaonc/show_dialog#9]
The pass/fail buttons should be able to:
* Set text
* Set icon

From the `Inputs` class.

Colors can already be set by the stylesheet.

**Comment by joaonc** [comment]
Add tests, inputs and resources (for icons).

* Have the ability to set icon from an external file.
* (nice to have) ability to set an image to the whole button (not just the icon).
  Note that this can be set in the CSS stylesheet.
  ```css
   QPushButton {
    image: url(/path/to/your/image.png);
   }
   ```
